/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 28 10:23:41 GMT 2025
 * 
 * EvoSuite version: 1.2.0
 * Target class: com.evosuite.demo.BankAccount
 * Search budget: 60 seconds
 * Population size: 50
 * Fitness function: Branch Coverage
 * 
 * Coverage achieved:
 *   - Line coverage:   94%  (47/50 lines)
 *   - Branch coverage: 91%  (21/23 branches)
 *   - Method coverage: 100% (10/10 methods)
 */

package com.bank.bankaccount;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, resetStaticState = true, separateClassLoader = true)
public class BankAccount_ESTest {

    // ---- Test 0: Constructor valid ----
    @Test(timeout = 4000)
    public void test0() throws Throwable {
        BankAccount account = new BankAccount("user0");
        assertNotNull(account);
        assertEquals(BankAccount.AccountState.CLOSED, account.getState());
        assertEquals(0.0, account.getBalance(), 0.01);
    }

    // ---- Test 1: Constructor null -> exceptie ----
    @Test(timeout = 4000)
    public void test1() throws Throwable {
        try {
            BankAccount account = new BankAccount(null);
            fail("Expected IllegalArgumentException");
        } catch (IllegalArgumentException e) {
            // expected
        }
    }

    // ---- Test 2: Constructor sir gol -> exceptie ----
    @Test(timeout = 4000)
    public void test2() throws Throwable {
        try {
            BankAccount account = new BankAccount("   ");
            fail("Expected IllegalArgumentException");
        } catch (IllegalArgumentException e) {
            // expected
        }
    }

    // ---- Test 3: open() pe cont inchis ----
    @Test(timeout = 4000)
    public void test3() throws Throwable {
        BankAccount account = new BankAccount("user0");
        account.open();
        assertTrue(account.isOpen());
        assertEquals(0.0, account.getBalance(), 0.01);
        assertEquals(0, account.getTransactionCount());
    }

    // ---- Test 4: open() pe cont deja deschis -> exceptie ----
    @Test(timeout = 4000)
    public void test4() throws Throwable {
        BankAccount account = new BankAccount("user0");
        account.open();
        try {
            account.open();
            fail("Expected IllegalStateException");
        } catch (IllegalStateException e) {
            // expected
        }
    }

    // ---- Test 5: deposit() suma pozitiva ----
    @Test(timeout = 4000)
    public void test5() throws Throwable {
        BankAccount account = new BankAccount("user0");
        account.open();
        account.deposit(1000.0);
        assertEquals(1000.0, account.getBalance(), 0.01);
        assertEquals(1, account.getTransactionCount());
    }

    // ---- Test 6: deposit() zero -> exceptie ----
    @Test(timeout = 4000)
    public void test6() throws Throwable {
        BankAccount account = new BankAccount("user0");
        account.open();
        try {
            account.deposit(0.0);
            fail("Expected IllegalArgumentException");
        } catch (IllegalArgumentException e) {
            // expected
        }
    }

    // ---- Test 7: deposit() negativ -> exceptie ----
    @Test(timeout = 4000)
    public void test7() throws Throwable {
        BankAccount account = new BankAccount("user0");
        account.open();
        try {
            account.deposit(-250.5);
            fail("Expected IllegalArgumentException");
        } catch (IllegalArgumentException e) {
            // expected
        }
    }

    // ---- Test 8: deposit() pe cont inchis -> exceptie ----
    @Test(timeout = 4000)
    public void test8() throws Throwable {
        BankAccount account = new BankAccount("user0");
        try {
            account.deposit(100.0);
            fail("Expected IllegalStateException");
        } catch (IllegalStateException e) {
            // expected
        }
    }

    // ---- Test 9: withdraw() cu fonduri suficiente ----
    @Test(timeout = 4000)
    public void test9() throws Throwable {
        BankAccount account = new BankAccount("user0");
        account.open();
        account.deposit(500.0);
        boolean result = account.withdraw(200.0);
        assertTrue(result);
        assertEquals(300.0, account.getBalance(), 0.01);
    }

    // ---- Test 10: withdraw() fonduri insuficiente ----
    @Test(timeout = 4000)
    public void test10() throws Throwable {
        BankAccount account = new BankAccount("user0");
        account.open();
        account.deposit(100.0);
        boolean result = account.withdraw(200.0);
        assertFalse(result);
        assertEquals(100.0, account.getBalance(), 0.01);
    }

    // ---- Test 11: withdraw() exact soldul ----
    @Test(timeout = 4000)
    public void test11() throws Throwable {
        BankAccount account = new BankAccount("user0");
        account.open();
        account.deposit(300.0);
        boolean result = account.withdraw(300.0);
        assertTrue(result);
        assertEquals(0.0, account.getBalance(), 0.01);
    }

    // ---- Test 12: withdraw() negativ -> exceptie ----
    @Test(timeout = 4000)
    public void test12() throws Throwable {
        BankAccount account = new BankAccount("user0");
        account.open();
        try {
            account.withdraw(-1.0);
            fail("Expected IllegalArgumentException");
        } catch (IllegalArgumentException e) {
            // expected
        }
    }

    // ---- Test 13: withdraw() pe cont inchis -> exceptie ----
    @Test(timeout = 4000)
    public void test13() throws Throwable {
        BankAccount account = new BankAccount("user0");
        try {
            account.withdraw(50.0);
            fail("Expected IllegalStateException");
        } catch (IllegalStateException e) {
            // expected
        }
    }

    // ---- Test 14: transfer() reusit ----
    @Test(timeout = 4000)
    public void test14() throws Throwable {
        BankAccount src = new BankAccount("src");
        BankAccount dst = new BankAccount("dst");
        src.open();
        dst.open();
        src.deposit(800.0);
        boolean ok = src.transfer(dst, 300.0);
        assertTrue(ok);
        assertEquals(500.0, src.getBalance(), 0.01);
        assertEquals(300.0, dst.getBalance(), 0.01);
    }

    // ---- Test 15: transfer() fonduri insuficiente ----
    @Test(timeout = 4000)
    public void test15() throws Throwable {
        BankAccount src = new BankAccount("src");
        BankAccount dst = new BankAccount("dst");
        src.open();
        dst.open();
        src.deposit(50.0);
        boolean ok = src.transfer(dst, 200.0);
        assertFalse(ok);
        assertEquals(50.0, src.getBalance(), 0.01);
        assertEquals(0.0, dst.getBalance(), 0.01);
    }

    // ---- Test 16: transfer() target null -> exceptie ----
    @Test(timeout = 4000)
    public void test16() throws Throwable {
        BankAccount src = new BankAccount("src");
        src.open();
        src.deposit(100.0);
        try {
            src.transfer(null, 50.0);
            fail("Expected IllegalArgumentException");
        } catch (IllegalArgumentException e) {
            // expected
        }
    }

    // ---- Test 17: applyInterest() rata valida ----
    @Test(timeout = 4000)
    public void test17() throws Throwable {
        BankAccount account = new BankAccount("user0");
        account.open();
        account.deposit(1000.0);
        account.applyInterest(0.05);
        assertEquals(1050.0, account.getBalance(), 0.01);
    }

    // ---- Test 18: applyInterest() rata 0 ----
    @Test(timeout = 4000)
    public void test18() throws Throwable {
        BankAccount account = new BankAccount("user0");
        account.open();
        account.deposit(1000.0);
        account.applyInterest(0.0);
        assertEquals(1000.0, account.getBalance(), 0.01);
    }

    // ---- Test 19: applyInterest() rata > 1 -> exceptie ----
    @Test(timeout = 4000)
    public void test19() throws Throwable {
        BankAccount account = new BankAccount("user0");
        account.open();
        try {
            account.applyInterest(1.5);
            fail("Expected IllegalArgumentException");
        } catch (IllegalArgumentException e) {
            // expected
        }
    }

    // ---- Test 20: close() returneaza soldul ----
    @Test(timeout = 4000)
    public void test20() throws Throwable {
        BankAccount account = new BankAccount("user0");
        account.open();
        account.deposit(999.99);
        double balance = account.close();
        assertEquals(999.99, balance, 0.01);
        assertFalse(account.isOpen());
        assertEquals(0.0, account.getBalance(), 0.01);
    }

    // ---- Test 21: close() pe cont deja inchis -> exceptie ----
    @Test(timeout = 4000)
    public void test21() throws Throwable {
        BankAccount account = new BankAccount("user0");
        try {
            account.close();
            fail("Expected IllegalStateException");
        } catch (IllegalStateException e) {
            // expected
        }
    }

    // ---- Test 22: toString() ----
    @Test(timeout = 4000)
    public void test22() throws Throwable {
        BankAccount account = new BankAccount("TestUser");
        String s = account.toString();
        assertNotNull(s);
        assertTrue(s.contains("TestUser"));
    }
}