/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 28 18:36:18 GMT 2026
 */

package com.bank.bankaccount;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.bank.bankaccount.BankAccount;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class BankAccount_ESTest extends BankAccount_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount("+(uHlz~b2;?0$vcN7");
      bankAccount0.open();
      boolean boolean0 = bankAccount0.isOpen();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount("1|Le.Ev");
      boolean boolean0 = bankAccount0.isOpen();
      assertFalse(boolean0);
      assertEquals(0, bankAccount0.getTransactionCount());
      assertEquals(0.0, bankAccount0.getBalance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount(">C6,M:XY^");
      // Undeclared exception!
      try { 
        bankAccount0.close();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Cannot close: account is not open
         //
         verifyException("com.bank.bankaccount.BankAccount", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount("J&<5CpmZf5!n(TT:~a");
      bankAccount0.open();
      double double0 = bankAccount0.close();
      assertEquals(0, bankAccount0.getTransactionCount());
      assertEquals(0.0, bankAccount0.getBalance(), 0.01);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount("r6<m(u}-xXoY:_");
      bankAccount0.open();
      bankAccount0.applyInterest(1.0);
      assertEquals(0.0, bankAccount0.getBalance(), 0.01);
      assertEquals(0, bankAccount0.getTransactionCount());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount("J&<5CpmZf5!n(TT:~a");
      bankAccount0.open();
      // Undeclared exception!
      try { 
        bankAccount0.applyInterest(2421.188);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Interest rate must be between 0 and 1
         //
         verifyException("com.bank.bankaccount.BankAccount", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount("g(K");
      // Undeclared exception!
      try { 
        bankAccount0.applyInterest(0.0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Cannot apply interest: account is not open
         //
         verifyException("com.bank.bankaccount.BankAccount", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount("J&<5CpmZf5!n(TT:~a");
      bankAccount0.open();
      // Undeclared exception!
      try { 
        bankAccount0.applyInterest((-2343.171264695));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Interest rate must be between 0 and 1
         //
         verifyException("com.bank.bankaccount.BankAccount", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount("J&<5CpmZf5!n(TT:~a");
      bankAccount0.open();
      boolean boolean0 = bankAccount0.transfer(bankAccount0, 735.0877891387286);
      assertEquals(0.0, bankAccount0.getBalance(), 0.01);
      assertFalse(boolean0);
      assertEquals(0, bankAccount0.getTransactionCount());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount(">C6,M:XY^");
      // Undeclared exception!
      try { 
        bankAccount0.transfer(bankAccount0, (-1.0));
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Target account is not open
         //
         verifyException("com.bank.bankaccount.BankAccount", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount("E=h1x_nZqKC");
      // Undeclared exception!
      try { 
        bankAccount0.transfer((BankAccount) null, (-2274.4835282));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Target account cannot be null
         //
         verifyException("com.bank.bankaccount.BankAccount", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount("Y");
      bankAccount0.open();
      // Undeclared exception!
      try { 
        bankAccount0.withdraw((-4303.394627));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Withdrawal amount must be positive
         //
         verifyException("com.bank.bankaccount.BankAccount", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount("E=h1x_nZqKC");
      // Undeclared exception!
      try { 
        bankAccount0.withdraw((-2083.394684));
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Cannot withdraw: account is not open
         //
         verifyException("com.bank.bankaccount.BankAccount", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount("1|Le.Ev");
      // Undeclared exception!
      try { 
        bankAccount0.deposit(0.0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Cannot deposit: account is not open
         //
         verifyException("com.bank.bankaccount.BankAccount", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount("+(uHlz~b2;?0$vcN7");
      bankAccount0.open();
      bankAccount0.deposit(1.0);
      boolean boolean0 = bankAccount0.transfer(bankAccount0, 1.0);
      assertEquals(3, bankAccount0.getTransactionCount());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount("r<m(u}-xXoY_");
      bankAccount0.open();
      // Undeclared exception!
      try { 
        bankAccount0.open();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Account is already open
         //
         verifyException("com.bank.bankaccount.BankAccount", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount("J&<5CpmZf5!n(TT:~a");
      bankAccount0.open();
      // Undeclared exception!
      try { 
        bankAccount0.deposit((-277.70885063));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Deposit amount must be positive, got: -277.70885063
         //
         verifyException("com.bank.bankaccount.BankAccount", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      BankAccount bankAccount0 = null;
      try {
        bankAccount0 = new BankAccount("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Owner name cannot be null or empty
         //
         verifyException("com.bank.bankaccount.BankAccount", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      BankAccount bankAccount0 = null;
      try {
        bankAccount0 = new BankAccount((String) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Owner name cannot be null or empty
         //
         verifyException("com.bank.bankaccount.BankAccount", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount("1|Le.Ev");
      double double0 = bankAccount0.getBalance();
      assertEquals(0, bankAccount0.getTransactionCount());
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount(">C6,M:XY^");
      String string0 = bankAccount0.toString();
      assertEquals("BankAccount[owner=>C6,M:XY^, state=CLOSED, balance=0.00, transactions=0]", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount("g(K");
      bankAccount0.getState();
      assertEquals(0.0, bankAccount0.getBalance(), 0.01);
      assertEquals(0, bankAccount0.getTransactionCount());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount("E=h1x_nZqKC");
      bankAccount0.getOwner();
      assertEquals(0, bankAccount0.getTransactionCount());
      assertEquals(0.0, bankAccount0.getBalance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      BankAccount bankAccount0 = new BankAccount("J&<5CpmZf5!n(TT:~a");
      int int0 = bankAccount0.getTransactionCount();
      assertEquals(0.0, bankAccount0.getBalance(), 0.01);
      assertEquals(0, int0);
  }
}
